language: python
sudo: required
dist: xenial

python:
  - 3.5.3  # minimum for aiohttp=3 and async-timeout=3
  - 3.5
  - 3.6.3
  - 3.6
  - 3.7
  - 3.8-dev
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.8-dev
  - python: nightly
  include:
  - python: 3.5.3
    env: COCRAWLER_LOGLEVEL=DEBUG
  - python: 3.5.3
    env: PYTHONASYNCIODEBUG=1

git:
  depth: 9999

install: "pip install -r requirements.txt"

script:
  - make test_coverage
after_success:
  coveralls
