sudo: false
group: travis_latest

language: python
python:
  - 3.5.3  # minimum for aiohttp=3 and async-timeout=3
  - 3.5
  - 3.6.0
  - 3.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7
  - python: nightly
  include:
  - python: 3.5.3
    env: COCRAWLER_LOGLEVEL=DEBUG
  - python: 3.5.3
    env: PYTHONASYNCIODEBUG=1
  - python: 3.7
    sudo: true

git:
  depth: 9999

install: "pip install -r requirements.txt"

script:
  - make test_coverage
after_success:
  coveralls
